import { StyleSheet } from 'react-native';

const estilos = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1A1A1D',
  },
  cabecalho: {
    position: 'relative',
    height: 200,
  },
  areaCapa: {
    height: 150,
    width: '100%',
    backgroundColor: '#333',
    overflow: 'hidden',
  },
  imagemCapa: {
    width: '100%',
    height: '100%',
    opacity: 0.7,
  },
  containerFoto: {
    position: 'absolute',
    bottom: 0,
    alignSelf: 'center',
    alignItems: 'center',
  },
  bordaFoto: {
    width: 110,
    height: 110,
    borderRadius: 55,
    borderWidth: 3,
    borderColor: '#1A1A1D',
    overflow: 'hidden',
    backgroundColor: '#333',
    alignItems: 'center',
    justifyContent: 'center',
  },
  fotoPerfil: {
    width: 104,
    height: 104,
    borderRadius: 52,
  },
  placeholderFoto: {
    width: 104,
    height: 104,
    borderRadius: 52,
    backgroundColor: '#333',
    alignItems: 'center',
    justifyContent: 'center',
  },
  botaoEditarFoto: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: '#ba68c8',
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#1A1A1D',
  },
  infoUsuario: {
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 20,
  },
  boasVindas: {
    fontSize: 18,
    color: 'white',
    marginBottom: 4,
  },
  nomeUsuario: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#ba68c8',
  },
  conteudoPrincipal: {
    flex: 1,
    paddingHorizontal: 16,
  },
  secaoReclamacoes: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 12,
    padding: 16,
    marginBottom: 80, // Espaço para o rodapé
  },
  tituloSecao: {
    fontSize: 20,
    fontWeight: 'bold',
    color: 'white',
    marginBottom: 16,
  },
  itemReclamacao: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
  },
  infoReclamacao: {
    flex: 1,
  },
  tituloReclamacao: {
    fontSize: 16,
    color: 'white',
    fontWeight: '500',
  },
  empresaReclamacao: {
    fontSize: 14,
    color: '#ba68c8',
    marginTop: 2,
  },
  dataReclamacao: {
    fontSize: 12,
    color: '#999',
    marginTop: 4,
  },
  statusReclamacao: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    minWidth: 90,
    alignItems: 'center',
  },
  respondida: {
    backgroundColor: 'rgba(39, 174, 96, 0.2)',
  },
  naoRespondida: {
    backgroundColor: 'rgba(231, 76, 60, 0.2)',
  },
  textoStatus: {
    fontSize: 12,
    fontWeight: 'bold',
    color: 'white',
  },
  semReclamacoes: {
    color: '#999',
    textAlign: 'center',
    marginVertical: 20,
  },
  botaoNovaReclamacao: {
    backgroundColor: '#ba68c8',
    borderRadius: 25,
    paddingVertical: 12,
    paddingHorizontal: 20,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
  },
  iconeBotao: {
    marginRight: 8,
  },
  textoBotao: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 16,
  },
  rodape: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: 'white',
    paddingVertical: 12,
    justifyContent: 'space-around',
    backgroundColor: '#1A1A1D',
  },
  itemRodape: {
    flex: 1,
    alignItems: 'center',
  },
  itemSelecionado: {
    flexDirection: 'column',
    alignItems: 'center',
    borderBottomWidth: 2,
    borderBottomColor: 'white',
    paddingBottom: 4,
  },
  itemNaoSelecionado: {
    flexDirection: 'column',
    alignItems: 'center',
    paddingBottom: 4,
  },
  textoRodape: {
    fontSize: 12,
    marginTop: 2,
  },

  // Estilos do modal
  centrarModal: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
  },
  conteudoModal: {
    width: '90%',
    maxHeight: '80%',
    backgroundColor: '#222',
    borderRadius: 12,
    overflow: 'hidden',
  },
  cabecalhoModal: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#ba68c8',
    paddingVertical: 15,
    paddingHorizontal: 20,
  },
  tituloModal: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  botaoFechar: {
    padding: 5,
  },
  formulario: {
    padding: 20,
  },
  campoFormulario: {
    marginBottom: 16,
  },
  labelFormulario: {
    color: 'white',
    fontSize: 14,
    marginBottom: 6,
  },
  inputFormulario: {
    backgroundColor: '#333',
    borderRadius: 8,
    padding: 12,
    color: 'white',
    borderWidth: 1,
    borderColor: '#444',
  },
  inputMultiline: {
    minHeight: 100,
  },
  botaoUploadImagem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#333',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#444',
    borderStyle: 'dashed',
    padding: 20,
  },
  textoUploadImagem: {
    color: '#ba68c8',
    marginLeft: 10,
    fontSize: 16,
  },
  previewContainer: {
    position: 'relative',
    marginBottom: 10,
  },
  previewImagem: {
    width: '100%',
    height: 200,
    borderRadius: 8,
    resizeMode: 'cover',
  },
  botaoRemoverImagem: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: 'rgba(231, 76, 60, 0.8)',
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  botaoEnviar: {
    backgroundColor: '#ba68c8',
    borderRadius: 25,
    paddingVertical: 14,
    paddingHorizontal: 20,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 20,
  },
  sucessoContainer: {
    padding: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  textoSucesso: {
    color: 'white',
    fontSize: 18,
    textAlign: 'center',
    marginTop: 20,
  },
});

export default estilos;
